"""Core Event Bus — Central event communication for the RPG system.

PHASE 1 — STABILIZE:
This module implements the EventBus as specified in rpg-design.txt Step 2.
It provides a simple, decoupled event system where all cross-system
communication flows through events rather than direct method calls.

PHASE 1.5 — ENFORCEMENT PATCH:
- Added source field to Event for system identity tracking
- Added event history for replay/debug power
- Added stronger cross-system call enforcement
- Added tick ID injection for temporal debugging

PHASE 1.6 — CRITICAL FIXES (rpg-design.txt):
- Fix #1: Clone events to prevent mutation side effects
- Fix #2: Enforce source field on all events
- Fix #3: Layer-based cross-system detection
- Fix #4: Proper setter for _current_tick (encapsulation)
- Fix #5: Bounded history to prevent memory leaks
- Fix #6: ContextVar reset edge case handling

ARCHITECTURE RULE:
This system must NOT directly call other systems.
Use EventBus for all cross-system communication.

Usage:
    bus = EventBus()
    bus.emit(Event("relationship_changed", {"npc_id": 1, "target_id": 2, "delta": 0.1}))
    events = bus.collect()  # Returns and clears all pending events
"""

from collections import deque
import copy
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
import inspect

# PHASE 3 — TIMELINE GRAPH
from .timeline_graph import TimelineGraph

# PHASE 5.2 — DETERMINISTIC CLOCK (rpg-design.txt Issue #2)
from .clock import DeterministicClock
from .determinism import DeterminismConfig, compute_deterministic_event_id


# Allowed layers for cross-system enforcement (Fix #3)
ALLOWED_LAYERS = {
    "app.rpg.core",
    "app.rpg.narrative",
    "app.rpg.world",
    "app.rpg.npc",
    "app.rpg.ai",
    "app.rpg.agent",
    "app.rpg.character",
    "app.rpg.quest",
    "app.rpg.choice",
    "app.rpg.cognitive",
    "app.rpg.story",
    "app.rpg.scene",
    "app.rpg.player",
    "app.rpg.memory",
    "app.rpg.systems",
    "app.rpg.events",
    "app.rpg.narration",
    "app.rpg.tools",
    "tests",
}


# PHASE 4 — EVENT CONTEXT (rpg-design.txt Issue #1)
@dataclass
class EventContext:
    """Causal context for event emission.

    Addresses rpg-design.txt Issue #1: Parent Chain Is NOT Guaranteed Correct.
    Instead of using a global _last_event_id, this class provides explicit
    causal context for each system's event emission.

    Usage in GameLoop:
        ctx = EventContext(parent_id=player_event.event_id)
        npc_system.update(ctx)
        world_system.tick(ctx)
    """
    parent_id: Optional[str] = None
    tick: Optional[int] = None
    source_system: Optional[str] = None


@dataclass
class Event:
    """A single game event with a type and payload.

    PHASE 2.5 — EVENT ORDERING + CAUSALITY TRACKING:
    - event_id: Unique identifier for deduplication and causal tracking
    - timestamp: High-resolution timestamp for ordering
    - parent_id: Reference to the event that caused this event

    PHASE 5.2 — DETERMINISTIC EVENT ID (rpg-design.txt Issue #1):
    - event_id is now generated by EventBus.next_event_id() instead of uuid4()
    - This ensures determinism, replay parity, and stable hashing

    PHASE 5.2 — DETERMINISTIC TIMESTAMP (rpg-design.txt Issue #2):
    - timestamp is now generated by DeterministicClock instead of time.time()
    - This ensures reproducibility in tests, replay, and simulation

    PHASE 5.2 — FIRST-CLASS TICK (rpg-design.txt Issue #4):
    - tick is now a first-class field on Event, not hidden in payload
    - This makes ordering reliable and removes hidden coupling

    Attributes:
        type: The event type/name (e.g., "relationship_changed", "combat_started").
        payload: Dictionary containing event-specific data.
        source: Optional source system identifier for tracing who did what.
        event_id: Unique sequential ID (e.g., "evt_1", "evt_2").
        timestamp: Deterministic timestamp from DeterministicClock.
        parent_id: Optional reference to the causally preceding event.
        tick: The tick number when this event was emitted.
    """
    type: str
    payload: Dict[str, Any] = field(default_factory=dict)
    source: Optional[str] = None
    event_id: Optional[str] = None
    timestamp: Optional[float] = None
    parent_id: Optional[str] = None
    # PHASE 5.2 — FIRST-CLASS TICK (rpg-design.txt Issue #4)
    tick: Optional[int] = None

    def __post_init__(self) -> None:
        """
        Event is intentionally passive.
        Deterministic event_id, timestamp, tick, and _seq are assigned by EventBus.emit().
        """
        pass

    def __repr__(self) -> str:
        return (
            f"Event(type={self.type!r}, payload={self.payload!r}, "
            f"source={self.source!r}, event_id={self.event_id!r})"
        )


class EventBus:
    """Central event bus for decoupled system communication.

    This implements the EventBus pattern from rpg-design.txt:
    - Systems emit events instead of directly calling other systems
    - Events are collected and processed in batch per game tick
    - Provides a clean separation of concerns between subsystems

    PHASE 5.2 — DETERMINISTIC EVENT ID (rpg-design.txt Issue #1):
    - _global_event_counter provides sequential, deterministic event IDs
    - next_event_id() classmethod generates IDs like "evt_1", "evt_2", etc.

    PHASE 5.2 — DETERMINISTIC CLOCK (rpg-design.txt Issue #2):
    - _clock is an optional DeterministicClock injected at construction
    - When set, provides deterministic timestamps for reproducibility

    PHASE 5.2 — MEMORY LEAK FIX (rpg-design.txt Issue #3):
    - _seen_event_ids_set is now pruned when the deque slides
    - This prevents unbounded memory growth during long sessions

    Attributes:
        _events: Internal list of pending events.
        _log: Optional log of all events ever emitted (for debugging).
        _enforce: If True, development-time enforcement checks are active.
    """


    def __init__(
        self,
        debug: bool = False,
        enforce: bool = False,
        clock: Optional["DeterministicClock"] = None,
        determinism: Optional["DeterminismConfig"] = None,
    ):
        """Initialize the EventBus.

        Args:
            debug: If True, log all events for debugging purposes.
            enforce: If True, enable development-time enforcement to detect misuse.
            clock: Optional DeterministicClock for deterministic timestamps.
                  When None, a default DeterministicClock is created.
            determinism: Optional DeterminismConfig for seeded deterministic IDs.
                        When None, defaults to DeterminismConfig(seed=0).
        """
        self._clock = clock or DeterministicClock(start_time=0.0, increment=0.001)
        self._determinism = determinism or DeterminismConfig()

        self._events: List[Event] = []
        self._log: Optional[List[Event]] = [] if debug else None
        self._history: List[Event] = []  # Complete event history for replay/debug
        self._debug = debug
        self._enforce = enforce
        self._current_tick: Optional[int] = None  # Current tick ID for temporal tracking
        self._max_history: int = 10000  # Fix #5: Bounded history to prevent memory leaks
        # PHASE 2.5 — DEDUPLICATION SAFETY: Track seen event IDs to prevent duplicates
        # PHASE 4 — MEMORY GROWTH FIX (rpg-design.txt Issue #6): Use deque for sliding window
        self._seen_event_ids: deque = deque(maxlen=100_000)
        self._seen_event_ids_set: set = set()  # For O(1) lookup

        # PHASE 3 — TIMELINE GRAPH: DAG of event causality
        self.timeline = TimelineGraph()

        # PHASE 5.1.5 — FIX #4: Sequence number for stable event ordering
        # This solves the issue where payload["tick"] may not exist,
        # timestamps are non-deterministic, and event_id randomness leaks in.
        self._seq: int = 0

    def set_tick(self, tick: int) -> None:
        """Set the current tick ID for temporal tracking.

        Fix #4: This is the ONLY way to set the current tick. Direct mutation
        of _current_tick is prohibited.

        Args:
            tick: The current tick number.
        """
        self._current_tick = tick

    def emit(
        self,
        event: Event,
        *,
        replay: bool = False,
        context: Optional[EventContext] = None,
    ) -> None:
        """Emit an event (adds to the internal queue).

        This is the ONLY way systems should communicate across boundaries.
        Instead of: world.update_relationship(npc_id, target_id, delta)
        Use: bus.emit(Event("relationship_changed", {...}))

        PHASE 2 — REPLAY ENGINE FIX #1:
        Events emitted during replay (replay=True) are NOT added to history.
        This prevents history duplication when replaying event logs:
            - Normal emit -> history grows
            - Replay emit  -> history stays clean
            - Result: replay is deterministic, no double-counting

        PHASE 4 — EVENT CONTEXT (rpg-design.txt Issue #1):
        Instead of using global _last_event_id for parent linking,
        use explicit EventContext for true causality:
            ctx = EventContext(parent_id=player_event.event_id)
            npc_system.update(ctx)
            world.update(ctx)

        Fix #1: Clone event to prevent external mutation side-effects.
        Fix #2: Enforce source field when enforcement is enabled.

        PHASE 5.1.5 — FIX #4: Assign sequence number for deterministic ordering.
        Every event gets a monotonically increasing sequence number that
        provides stable ordering independent of timestamps or event_id randomness.

        Args:
            event: The event to emit.
            replay: If True, event is from replay and won't be added to
                   history. This prevents history duplication during replay.
            context: Optional EventContext for causal parent linking.
                    If provided, overrides event.parent_id for true causality.

        Raises:
            RuntimeError: If enforcement is enabled and source is missing.
        """
        self.assert_event_usage()

        # PHASE 5.1.5 — FIX #4: Assign sequence number for stable ordering
        event._seq = self._seq
        self._seq += 1

        # PHASE 4 — EVENT CONTEXT: Apply context parent_id and tick if provided
        # This addresses rpg-design.txt Issue #1: Parent Chain Is NOT Guaranteed Correct
        if context is not None and (context.parent_id is not None or context.tick is not None):
            seq_before = getattr(event, "_seq", 0)
            event = Event(
                type=event.type,
                payload=event.payload,
                source=event.source,
                event_id=event.event_id,
                timestamp=event.timestamp,
                parent_id=context.parent_id if context.parent_id is not None else event.parent_id,
                tick=context.tick if context.tick is not None else event.tick,
            )
            # PHASE 5.1.5 FIX #4: Preserve sequence number when cloning
            event._seq = seq_before

        # Fix #2: Enforce source field when enforcement is enabled
        if self._enforce and not event.source:
            raise RuntimeError(
                f"Event '{event.type}' missing source. "
                "All events must declare origin system."
            )

        # Determine canonical tick:
        # 1) explicit event.tick if already present
        # 2) current bus tick otherwise
        event_tick = event.tick if event.tick is not None else self._current_tick

        # Deep-clone payload so caller-side nested mutation cannot affect:
        # - event bus stored state
        # - deterministic identity inputs
        payload = copy.deepcopy(event.payload)

        # Identity payload must NOT duplicate top-level tick.
        # tick participates in identity as its own first-class field.
        identity_payload = copy.deepcopy(payload)

        # Legacy compatibility payload for downstream systems:
        # keep tick mirrored into payload["tick"] for older consumers.
        if event_tick is not None:
            payload["tick"] = event_tick

        # Assign deterministic timestamp if missing
        if self._determinism.replay_mode and event.timestamp is None:
            raise RuntimeError(
                "Replay mode requires recorded event.timestamp; refusing fresh timestamp generation."
            )
        event_timestamp = event.timestamp if event.timestamp is not None else self._clock.now()

        # Assign deterministic event_id if missing
        original_seq = getattr(event, "_seq", 0)
        event_id = event.event_id
        if event_id is None:
            if self._determinism.replay_mode:
                raise RuntimeError(
                    "Replay mode requires recorded event.event_id; refusing fresh ID generation."
                )
            # Deterministic identity is execution-path based:
            # seed + canonical event content + causal parent + tick + seq.
            # It is versioned in determinism.py via IDENTITY_VERSION.
            event_id = compute_deterministic_event_id(
                seed=self._determinism.seed,
                event_type=event.type,
                payload=identity_payload,
                source=event.source,
                parent_id=event.parent_id,
                tick=event_tick,
                seq=original_seq,
            )

        # Check for duplicate events BEFORE cloning
        if event_id in self._seen_event_ids_set:
            return  # prevent duplicates

        # Correct deque/set synchronization:
        # remove the element that will be evicted before append
        if len(self._seen_event_ids) == self._seen_event_ids.maxlen:
            evicted = self._seen_event_ids[0]
            self._seen_event_ids_set.discard(evicted)
        self._seen_event_ids.append(event_id)
        self._seen_event_ids_set.add(event_id)

        # Store the payload with legacy tick injection for compatibility,
        # but compute identity from identity_payload above to avoid
        # double-representing tick in the identity function.
        cloned = Event(
            type=event.type,
            payload=payload,
            source=event.source,
            event_id=event_id,
            timestamp=event_timestamp,
            parent_id=event.parent_id,
            tick=event_tick,
        )
        # PHASE 5.1.5 FIX #4: Preserve sequence number when cloning
        cloned._seq = original_seq

        # Propagate canonical fields back to original event so callers can inspect them
        event.event_id = event_id
        event.timestamp = event_timestamp
        event.tick = event_tick
        event._seq = original_seq

        # Use the cloned event for the bus
        event = cloned

        if self._debug:
            print(f"[EVENT] {event.type} -> {event.payload}")

        if self._log is not None:
            self._log.append(event)

        # PHASE 2 FIX #1: Separate "history" vs "replay"
        # Only add to history during normal gameplay, NOT during replay.
        # This prevents:
        # - Duplicated causal chain
        # - Broken temporal reasoning
        # - NPC memory double-counting events
        # - Analytics becoming garbage
        if not replay:
            self._history.append(event)

            # Fix #5: Bounded history to prevent memory leaks
            if len(self._history) > self._max_history:
                self._history.pop(0)

        self._events.append(event)

        # PHASE 3 — TIMELINE GRAPH: Track event in DAG for branching timelines
        self.timeline.add_event(event.event_id, event.parent_id)

    def collect(self) -> List[Event]:
        """Collect and clear all pending events.

        This should be called once per game tick by the GameLoop.
        Returns a snapshot of events, then clears the internal queue.

        Returns:
            List of all events emitted since last collect() call.
        """
        events = self._events[:]
        self._events.clear()
        return events

    def peek(self) -> List[Event]:
        """Peek at pending events without clearing them.

        Returns:
            List of all pending events (does not modify internal state).
        """
        return self._events[:]

    def clear(self) -> None:
        """Clear all pending events without processing them."""
        self._events.clear()

    @property
    def pending_count(self) -> int:
        """Number of events currently in the queue."""
        return len(self._events)

    @property
    def log(self) -> Optional[List[Event]]:
        """Access the event log (if debug mode is enabled).

        Returns:
            List of all events ever emitted, or None if not in debug mode.
        """
        return self._log

    def get_history(self) -> List[Event]:
        """Return the raw event history (unsorted) for internal use.

        This method provides access to the underlying history list
        for modules that need to iterate events without sorting
        overhead. For most use cases, prefer history() which
        guarantees deterministic ordering.

        PHASE 5.1: Added to support compute_state_hash and
        validation modules that need direct history access.

        Returns:
            List of all events ever emitted (not cleared by collect),
            in insertion order (no sorting).
        """
        return list(self._history)

    def history(self) -> List[Event]:
        """Return a copy of the complete event history for replay/debug.

        PHASE 5.1.5 — DETERMINISTIC ORDERING FIX #4:
        Events are now sorted by (tick, _seq) instead of (tick, timestamp, event_id).
        
        PHASE 5.2 — FIRST-CLASS TICK (rpg-design.txt Issue #4):
        Sort uses event.tick (first-class field) instead of payload["tick"].
        This removes hidden coupling and ensures ordering is always reliable.

        PHASE 5.1 issues with old sort key:
        - payload["tick"] may not exist on all events
        - timestamps are non-deterministic outside tests
        - event_id randomness leaks into ordering

        The new _seq field provides a monotonic, deterministic sequence number
        assigned at emit time, giving stable ordering regardless of timestamps.

        Returns:
            List of all events ever emitted (not cleared by collect),
            sorted deterministically by (tick, _seq).
        """
        return sorted(
            self._history[:],
            key=lambda e: (
                getattr(e, "tick", 0),  # PHASE 5.2: use first-class tick field
                getattr(e, "_seq", 0),
            ),
        )

    def load_history(self, events: List[Event]) -> None:
        """Load event history (used for replay/bootstrap).

        Restores the EventBus into a deterministic state derived from
        previously recorded events.

        This method restores:
        - full history
        - pending queue reset
        - timeline graph
        - seen-event dedup state
        - sequence counter
        - current tick

        This is required so replay/bootstrap state matches a live run
        as closely as possible.
        """
        self._history = list(events)
        self._events.clear()
        if self._log is not None:
            self._log.clear()
            self._log.extend(self._history)

        # Rebuild deterministic bus state from loaded history
        self.timeline.clear()
        self._seen_event_ids.clear()
        self._seen_event_ids_set.clear()
        self._seq = 0
        self._current_tick = None

        for e in self._history:
            self.timeline.add_event(e.event_id, e.parent_id)

            if e.event_id is not None:
                if len(self._seen_event_ids) == self._seen_event_ids.maxlen:
                    evicted = self._seen_event_ids[0]
                    self._seen_event_ids_set.discard(evicted)
                self._seen_event_ids.append(e.event_id)
                self._seen_event_ids_set.add(e.event_id)

            self._seq = max(self._seq, getattr(e, "_seq", 0) + 1)
            if getattr(e, "tick", None) is not None:
                self._current_tick = max(self._current_tick or 0, e.tick)

    def reset(self) -> None:
        """Reset the bus state (clears queue, log, and history).

        Fix #6: Don't touch context vars here - that breaks nested contexts.
        Context var management is handled by GameLoop.

        PHASE 2.5 FIX: Also clear seen event IDs to allow fresh replay.
        PHASE 5.2: Also reset sequence counter for clean deterministic replay.
        """
        self._events.clear()
        if self._log is not None:
            self._log.clear()
        self._history.clear()
        self._current_tick = None
        self._seen_event_ids.clear()
        self._seen_event_ids_set.clear()
        # PHASE 3: Clear timeline graph on reset
        self.timeline.clear()
        # PHASE 5.2: Reset sequence counter for deterministic replay
        self._seq = 0

    def assert_event_usage(self):
        """Development-time enforcement to detect illegal cross-system calls.

        Fix #3: Use layer-based detection instead of fragile string matching.
        """
        if not self._enforce:
            return

        stack = inspect.stack()

        for frame in stack[2:]:  # skip emit + assert frames
            module = inspect.getmodule(frame[0])
            if not module:
                continue

            name = module.__name__

            # Fix #3: Detect direct cross-layer calls using allowed layers
            for layer in ALLOWED_LAYERS:
                if name.startswith(layer):
                    return

        raise RuntimeError(
            "Illegal call path detected. Systems must communicate via EventBus."
        )

    def current_head(self) -> Optional[str]:
        """Get the current head event ID for parent linking.

        Addresses rpg-design.txt Issue #8: GameLoop Pointer Is Weak.
        Instead of using history[-1].event_id, use this method for
        the true current head of the event stream.

        Returns:
            The event_id of the most recently emitted event, or None.
        """
        if self._history:
            return self._history[-1].event_id
        return None

    def set_replay_mode(self, enabled: bool = True) -> None:
        """Set replay mode to influence deterministic behavior.

        When replay mode is enabled, subsystems should avoid fresh side effects.

        Args:
            enabled: Whether replay mode is active.
        """
        self._determinism.replay_mode = enabled

    def is_replay_mode(self) -> bool:
        """Return whether replay mode is currently enabled."""
        return self._determinism.replay_mode

    # PHASE 3 — EVENT CREATION HELPER (PATCH 6)
    def create_event(
        self,
        type: str,
        payload: dict,
        source: str,
        parent_id: Optional[str] = None,
    ) -> Event:
        """Convenience factory for creating events with parent linking.

        Args:
            type: Event type/name.
            payload: Event payload data.
            source: Source system identifier.
            parent_id: Optional parent event ID for causal linking.

        Returns:
            A new Event instance with auto-generated event_id and timestamp.
        """
        return Event(
            type=type,
            payload=payload,
            source=source,
            parent_id=parent_id,
        )
