"""Action Executor — World mutation via events for autonomous NPCs.

This module implements the Action Executor from TIER 10 of the RPG design spec.

Purpose:
    Execute concrete actions generated by the Planner and produce
    world events. The Action Executor is the bridge between NPC
    intentions and world state changes.

The Problem:
    - Plans contain abstract action steps
    - Actions need to produce concrete world events
    - Events must follow the design rule: "Agents generate events,
      systems react to events" (no direct world state modification)

The Solution:
    ActionExecutor receives character + action dict, produces events
    that other systems (faction, economy, reputation) can react to.
    The executor only generates events; systems consume them.

Usage:
    executor = ActionExecutor()
    events = executor.execute(character, action, world_state)
    # Events are then processed by world systems

Architecture:
    Action Step dict
         ↓
    Action Handler Selection
         ↓
    Event Generation
         ↓
    Events fed to world systems

Design Rules:
    - DO NOT directly modify world state
    - ONLY generate events
    - Systems react to events
    - Include actor, target, and context in events
"""

from __future__ import annotations

from typing import Any, Callable, Dict, List, Optional


class ActionExecutor:
    """Executes NPC actions and produces world events.
    
    The ActionExecutor converts concrete action steps from plans
    into world events. These events are then consumed by other
    systems (faction, economy, reputation, plot) to update state.
    
    Critical Rule: The executor NEVER directly modifies world state.
    It only generates events that other systems react to.
    
    Action Types:
    - increase_power: Faction power growth event
    - negotiate: Alliance/diplomacy events
    - gather_forces: Military preparation
    - attack: Conflict event
    - gather_resources: Resource accumulation
    - travel: Movement event
    - deliver: Aid/quest completion
    - scout: Information gathering
    - collect: Resource collection
    - prepare: Preparation phase
    - meet: Meeting/conference
    - agree: Agreement reached
    - fortify: Defensive preparations
    - wait: No significant event
    
    Usage:
        executor = ActionExecutor()
        events = executor.execute(character, {"action": "attack", "target": "enemy"})
        for event in events:
            world_systems.process(event)
    """
    
    def __init__(self):
        """Initialize the ActionExecutor."""
        self._handlers: Dict[str, Callable] = {}
        self._register_default_handlers()
        
    def _register_default_handlers(self) -> None:
        """Register default action handlers."""
        self._handlers["increase_power"] = self._handle_increase_power
        self._handlers["negotiate"] = self._handle_negotiate
        self._handlers["gather_forces"] = self._handle_gather_forces
        self._handlers["attack"] = self._handle_attack
        self._handlers["gather_resources"] = self._handle_gather_resources
        self._handlers["travel"] = self._handle_travel
        self._handlers["deliver"] = self._handle_deliver
        self._handlers["scout"] = self._handle_scout
        self._handlers["collect"] = self._handle_collect
        self._handlers["prepare"] = self._handle_prepare
        self._handlers["meet"] = self._handle_meet
        self._handlers["agree"] = self._handle_agree
        self._handlers["fortify"] = self._handle_fortify
        self._handlers["wait"] = self._handle_wait
    
    def execute(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Optional[Dict[str, Any]] = None,
    ) -> List[Dict[str, Any]]:
        """Execute an action and return generated events.
        
        Args:
            character: Character performing the action.
            action: Action dict with at least "action" key.
            world_state: Optional world state for context.
            
        Returns:
            List of event dicts generated by the action.
        """
        action_type = action.get("action", "wait")
        handler = self._handlers.get(action_type, self._handle_unknown)
        
        try:
            events = handler(character, action, world_state or {})
            return events
        except Exception:
            return [{
                "type": "action_error",
                "action": action_type,
                "actor": getattr(character, "id", "unknown"),
                "error": f"Failed to execute {action_type}",
            }]
    
    def register_handler(
        self,
        action_type: str,
        handler: Callable[[Any, Dict[str, Any], Dict[str, Any]], List[Dict[str, Any]]],
    ) -> None:
        """Register a custom action handler.
        
        Args:
            action_type: Action type string to handle.
            handler: Callable(character, action, world_state) -> list of events.
        """
        self._handlers[action_type] = handler
    
    def get_available_actions(self) -> List[str]:
        """Get list of registered action types.
        
        Returns:
            List of action type strings.
        """
        return list(self._handlers.keys())
    
    # === Default Action Handlers ===
    # Each handler: (character, action, world_state) -> list of events
    
    def _handle_increase_power(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle power increase action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of power_growth events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        faction_id = action.get("target", char_id)
        
        events.append({
            "type": "power_growth",
            "actor": char_id,
            "faction": faction_id,
            "description": f"{char_id} increases their power",
            "importance": 0.3,
        })
        
        return events
    
    def _handle_negotiate(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle negotiation action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of negotiation/diplomacy events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        target = action.get("target", "unknown")
        
        events.append({
            "type": "diplomatic_meeting",
            "actor": char_id,
            "target_faction": target,
            "description": f"{char_id} opens negotiations with {target}",
            "importance": 0.4,
        })
        
        return events
    
    def _handle_gather_forces(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle force gathering action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of military preparation events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        target = action.get("target", "")
        
        events.append({
            "type": "military_preparation",
            "actor": char_id,
            "target": target,
            "description": f"{char_id} is gathering forces",
            "importance": 0.5,
        })
        
        return events
    
    def _handle_attack(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle attack action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of conflict events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        target = action.get("target", "unknown")
        
        events.append({
            "type": "faction_conflict",
            "attacker": char_id,
            "target": target,
            "description": f"{char_id} attacks {target}",
            "importance": 0.7,
        })
        
        return events
    
    def _handle_gather_resources(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle resource gathering action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of resource events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        
        events.append({
            "type": "resource_gathering",
            "actor": char_id,
            "description": f"{char_id} gathers resources",
            "importance": 0.3,
        })
        
        return events
    
    def _handle_travel(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle travel action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of travel events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        target = action.get("target", "destination")
        
        events.append({
            "type": "travel",
            "actor": char_id,
            "destination": target,
            "description": f"{char_id} travels to {target}",
            "importance": 0.2,
        })
        
        return events
    
    def _handle_deliver(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle delivery action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of delivery/aid events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        target = action.get("target", "unknown")
        
        events.append({
            "type": "aid_delivered",
            "actor": char_id,
            "recipient": target,
            "description": f"{char_id} delivers aid to {target}",
            "importance": 0.5,
        })
        
        return events
    
    def _handle_scout(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle scouting action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of scouting events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        
        events.append({
            "type": "scouting",
            "actor": char_id,
            "description": f"{char_id} scouts the area",
            "importance": 0.2,
        })
        
        return events
    
    def _handle_collect(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle collection action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of collection events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        
        events.append({
            "type": "resource_collection",
            "actor": char_id,
            "description": f"{char_id} collects resources",
            "importance": 0.3,
        })
        
        return events
    
    def _handle_prepare(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle prepare action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of preparation events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        
        events.append({
            "type": "preparation",
            "actor": char_id,
            "description": f"{char_id} prepares for upcoming action",
            "importance": 0.2,
        })
        
        return events
    
    def _handle_meet(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle meeting action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of meeting events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        target = action.get("target", "unknown")
        
        events.append({
            "type": "meeting",
            "participants": [char_id, target],
            "description": f"{char_id} meets with {target}",
            "importance": 0.3,
        })
        
        return events
    
    def _handle_agree(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle agreement action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of agreement events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        target = action.get("target", "unknown")
        
        events.append({
            "type": "agreement",
            "participants": [char_id, target],
            "description": f"{char_id} reaches agreement with {target}",
            "importance": 0.5,
        })
        
        return events
    
    def _handle_fortify(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle fortification action.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            List of fortification events.
        """
        events = []
        char_id = getattr(character, "id", "unknown")
        
        events.append({
            "type": "fortification",
            "actor": char_id,
            "description": f"{char_id} fortifies their position",
            "importance": 0.4,
        })
        
        return events
    
    def _handle_wait(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle wait action (no event).
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            Empty list (no events from waiting).
        """
        return []
    
    def _handle_unknown(
        self,
        character: Any,
        action: Dict[str, Any],
        world_state: Dict[str, Any],
    ) -> List[Dict[str, Any]]:
        """Handle unknown action type.
        
        Args:
            character: Acting character.
            action: Action dict.
            world_state: World state.
            
        Returns:
            Error event.
        """
        char_id = getattr(character, "id", "unknown")
        action_type = action.get("action", "unknown")
        
        return [{
            "type": "unknown_action",
            "actor": char_id,
            "action": action_type,
            "description": f"{char_id} attempted unknown action: {action_type}",
            "importance": 0.1,
        }]