"""Agent System — Orchestrator for autonomous NPC agent system.

This module implements the Agent System orchestrator from TIER 10 of the RPG design spec.

Purpose:
    Orchestrate the full autonomous NPC decision-making pipeline:
    1. Select which NPCs act this tick (Scheduler)
    2. Decide what they want to do (Agent Brain)
    3. Plan how to do it (Planner)
    4. Execute their plans (Action Executor)
    5. Generate events for world systems to react to

The Problem:
    - Individual agent components exist but aren't coordinated
    - Plans need to persist across ticks
    - Events from NPCs need to be collected and returned
    - Integration with PlayerLoop needs a single entry point

The Solution:
    AgentSystem wraps all agent components and provides a single
    update() method that:
    1. Selects active NPCs via scheduler
    2. Continues existing plans or creates new ones
    3. Executes plan steps
    4. Returns all generated events

Usage:
    agents = AgentSystem(max_per_tick=5)
    events = agents.update(characters, world_state)
    # events feed into world systems

Architecture:
    PlayerLoop.step()
         ↓
    AgentSystem.update()
         ↓
    AgentScheduler.select_agents()
         ↓
    For each active NPC:
        if has active plan:
            plan.next() → executor.execute() → events
        else:
            brain.decide() → planner.create_plan() → store plan
         ↓
    Return all events
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from .agent_brain import AgentBrain
from .planner import Plan, Planner
from .action_executor import ActionExecutor
from .agent_scheduler import AgentScheduler


class AgentSystem:
    """Orchestrates autonomous NPC agent system.
    
    The AgentSystem is the main entry point for NPC autonomy.
    It coordinates the brain, planner, executor, and scheduler
    to produce world events from NPC decisions.
    
    Integration Points:
        - PlayerLoop.step(): Called after simulation tick
        - Faction System: Faction events from agent actions
        - Reputation Engine: Player reputation effects
        - Plot Engine: Quest-related events
        
    Usage:
        agents = AgentSystem(max_per_tick=5)
        
        # In PlayerLoop.step():
        agent_events = agents.update(
            characters=self.characters.characters,
            world_state=self._get_world_state(),
        )
        world_events.extend(agent_events)
    
    Attributes:
        brain: AgentBrain for NPC decision-making.
        planner: Planner for multi-step planning.
        executor: ActionExecutor for event generation.
        scheduler: AgentScheduler for NPC selection.
    """
    
    def __init__(
        self,
        max_per_tick: int = 5,
        brain: Optional[AgentBrain] = None,
        planner: Optional[Planner] = None,
        executor: Optional[ActionExecutor] = None,
        scheduler: Optional[AgentScheduler] = None,
    ):
        """Initialize AgentSystem.
        
        Args:
            max_per_tick: Maximum NPCs to act per tick.
            brain: Custom AgentBrain (or use default).
            planner: Custom Planner (or use default).
            executor: Custom ActionExecutor (or use default).
            scheduler: Custom AgentScheduler (or use default).
        """
        self.brain = brain or AgentBrain()
        self.planner = planner or Planner()
        self.executor = executor or ActionExecutor()
        self.scheduler = scheduler or AgentScheduler(max_per_tick=max_per_tick)
        
        # Active plans: char_id -> Plan
        self.active_plans: Dict[str, Plan] = {}
    
    def update(
        self,
        characters: Dict[str, Any],
        world_state: Optional[Dict[str, Any]] = None,
    ) -> List[Dict[str, Any]]:
        """Process autonomous NPC actions for this tick.
        
        This is the main entry point. It:
        1. Selects which NPCs act (scheduler)
        2. For each active NPC:
           a. Continue existing plan or create new one
           b. Execute plan step
           c. Collect events
        3. Remove completed/failed plans
        
        Args:
            characters: Dict of char_id → Character objects.
            world_state: World state dict for context.
            
        Returns:
            List of event dicts generated by NPC actions.
        """
        events: List[Dict[str, Any]] = []
        
        # Step 1: Select which NPCs act this tick
        active_ids = self.scheduler.select_agents(characters, world_state)
        
        # Step 2: Process each active NPC
        for cid in active_ids:
            char = characters.get(cid)
            if char is None:
                continue
            
            # Step 2a: Continue existing plan if available
            if cid in self.active_plans:
                plan = self.active_plans[cid]
                step = plan.next()
                
                if step is not None:
                    # Execute this plan step
                    step_events = self.executor.execute(char, step, world_state)
                    events.extend(step_events)
                    
                    # Remove plan if complete
                    if plan.is_complete or plan.failed:
                        del self.active_plans[cid]
                else:
                    # Plan exhausted, remove it
                    del self.active_plans[cid]
                
                # Continue to next NPC (don't create new plan this tick)
                continue
            
            # Step 2b: Create new plan via Agent Brain
            intention = self.brain.decide(char, world_state or {})
            
            if intention is None:
                # NPC has no goals, skip
                continue
            
            # Don't plan for idle NPCs
            intention_type = intention.get("type", "idle")
            if intention_type == "idle":
                continue
            
            plan = self.planner.create_plan(intention)
            self.active_plans[cid] = plan
            
            # Execute first step of new plan
            step = plan.next()
            if step:
                step_events = self.executor.execute(char, step, world_state)
                events.extend(step_events)
                
                # Remove if plan was only 1 step
                if plan.is_complete or plan.failed:
                    del self.active_plans[cid]
        
        return events
    
    def get_active_plan_count(self) -> int:
        """Get number of NPCs with active plans.
        
        Returns:
            Number of active plans.
        """
        return len(self.active_plans)
    
    def get_active_plan(self, char_id: str) -> Optional[Plan]:
        """Get the active plan for a character.
        
        Args:
            char_id: Character ID.
            
        Returns:
            Plan object, or None if no active plan.
        """
        return self.active_plans.get(char_id)
    
    def cancel_plan(self, char_id: str) -> Optional[Plan]:
        """Cancel a character's active plan.
        
        Args:
            char_id: Character ID.
            
        Returns:
            Cancelled plan, or None if no plan.
        """
        return self.active_plans.pop(char_id, None)
    
    def get_scheduler_stats(self) -> Dict[str, Any]:
        """Get scheduler statistics.
        
        Returns:
            Dict with scheduling stats.
        """
        return {
            "active_plans": self.get_active_plan_count(),
            "selection_stats": self.scheduler.get_selection_stats(),
            "last_selected": self.scheduler.get_last_selected(),
        }
    
    def reset(self) -> None:
        """Reset all agent system state."""
        self.active_plans.clear()
        self.scheduler.reset()